name: Java CI

on: [push]

jobs:

  build_faiss:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build Faiss in docker
      uses: ./.github/actions

    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3
    
    - uses: actions/upload-artifact@v2
      with:
        name: faiss_JNI_and_SO
        path: cpu/src/main/resources
    

  build:
    needs: build_faiss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml


