name: Java CI

on: [push]

jobs:

  build_faiss:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build Faiss in docker
      uses: ./.github/actions

    # - name: Debugging with tmate
    #   uses: mxschmitt/action-tmate@v3
    
    - uses: actions/upload-artifact@v2
      with:
        name: faiss_JNI_and_SO
        path: build
    

  build:
    needs: build_faiss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: faiss_JNI_and_SO
          path: build_copy
      - name: Move
        run: rm -rf src/main/java/com/vectorsearch/faiss/swig
        run: cp -r build_copy/src/main/java/com/vectorsearch/faiss/swig src/main/java/com/vectorsearch/faiss/swig
        run: rm -rf src/main/resources
        run: cp -r build_copy/src/main/resources src/main/resources

      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}